### PR TITLE
Support for masking a keystore password

### LINKED ISSUE #17: We should be able to mask the secret value
We should be able to mask the secret `quarkus.file.vault.provider.db1.secret`

```
quarkus.file.vault.provider.db1.path=dbpasswords.p12
quarkus.file.vault.provider.db1.secret=storepassword
quarkus.file.vault.provider.db1.alias=quarkus_test
```

### PR DESCRIPTION
**Pull request by pedro-hos**
Closes #17

### CODE REVIEW

**Comment by pedro-hos** [comment]
Hi @sberyozkin here is the PR. I will really appreciate some feedback on that. 
Thanks

**Comment by sberyozkin** [comment]
@pedro-hos Nice work, thanks. Looking now...

**Comment by sberyozkin** [comment]
@pedro-hos I think we should make a `salt` parameter required (it is too easy right now to use a default salt) and it makes it somewhat easier to attack, I propose that no default salt is provided. And if the user does not provide its own salt then `VaultUtils` can generate and output the one for the user using `SecureRandom`. Please look at it.

**Comment by sberyozkin** [comment]
@pedro-hos In fact I think we should use a different algorithm altogether, `AES/GCM/NoPadding`, which will make `SALT` and `ITERATION_COUNT` unnecessary - which is something that can be hard for the customer to choose right. There are various resource online which in general, while acknowledging pros/cons of both `AES/CBC` and `AES/GSM` which recommend `AES/GCM`. `AES/GSM` is also used in Quarkus to encrypt in `FormAuthenticationMechanism`, Stuart Douglas and Pedro Silva (also Keycloak team) looked at that code as far as I recall.

Let me play with you branch a bit and I'll push another commit which we can revert, or squash if you will agree with the changes

Thanks

**Comment by sberyozkin** [comment]
@pedro-hos I only force pushed the formatting fix

**Comment by pedro-hos** [comment]
Hi, @sberyozkin thanks for looking at this. Regarding the random `salt`, I liked that idea, maybe we can have the encrypt key random as well. But, I also agree that this is another visible piece of configuration, and in a possible attack, it could be a problem.

**Comment by sberyozkin** [comment]
hey @pedro-hos I've added a commit which now uses `Aes/Gsm`, it should be a bit better. Have a look please.

Yes, I guess we should just do SHA256 hash, salt and iteration count is likely not something that is not something we should expect users to set correctly, while having the default salt in the open source is not particularly secure either.

Indeed, I think we should make providing a secret key optional - if it is not provided then we should auto-generate it and print out alongside the masked value.

I'll have a look tomorrow.

**Comment by sberyozkin** [comment]
We can make encryption utils a dedicated module a bit later on to minimize the duplication

**Comment by pedro-hos** [comment]
Hey @sberyozkin I've tested, and the changes sound good :-D I've also tested and everything is working. I've made the squash also. Thanks again \o

**Comment by sberyozkin** [comment]
@pedro-hos Thanks, I'm going to continue today/tomorrow, the plan so far is to
* drop salt/iteration count and use SHA256 hash (we can return to the salt/count if necessary)
* make sure the user provided secret key is at least 16 chars long
* generate the secret key if the user does not provide the key and print this key along the encrypted value

**Comment by sberyozkin** [comment]
Hi @pedro-hos I've done a few more updates and dropped the salt/iteration count for now as SHA256 hashing of the existing key should be sufficient, but I've also added a restriction that the encryption key must be at least 16 characters long. Since the algorithm is `AES GSM 128`, the key size less than `128 bits` would be considered not very secure. I think I might change it to  `AES GSM 256` as well later on.
I've done a few other cosmetic updates, in the file vault provider I thought the condition should be made stricter, we can't really start decrypting if the default `secret` is provided. I did not really to mess with your code,

One thing which can be really useful is for the encryption key be auto-generated. But it would mean it would have to be represented as Base64URL encoded (FYI Base64URL is better as the trailing `==` which are typically available in `Base64` are not added). Base64URL is used everywhere in JOSE (JWT tokens, etc).

But if the auto-generated encryption key is saved in a Base64URL encoded format then it means that if a user provides a  custom encryption key of their own then it also has to be Base64URL encoded. I think it is reasonable, it is really not a secure approach for users to start supplying some strings, if we support the auto-generation of the keys then the users would always get a securely generated 16 or 32 chars long key, as the key factory would use a secure random.

So the fact  that if  user provides a  custom encryption key of their own then it also has to be Base64URL encoded it is not really a restriction, if they have some value of their own then it would be straightforward to apply base64url encoding to it, but in most cases I'd just expect the users this tool generate a secret key.

What do you think ?

**Comment by sberyozkin** [comment]
@pedro-hos I think, if you are OK with the current changes then I'll merge this PR and then I can open another PR to discuss specifically focused around making an encryption key optional for it to be auto-generated

**Comment by pedro-hos** [comment]
@sberyozkin thanks for your help here. I am ok with the changes, we can close this issue now; I am out today, but on Sunday when I will get back to work, I will test the new release. Many thanks @sberyozkin

**Comment by sberyozkin** [comment]
Thanks @pedro-hos

**Review by sberyozkin — APPROVED** [review]

**Comment by pedro-hos** [comment]
@sberyozkin I have finished the test. Everything working fine. :-)

**Pull request merged**
